# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(null=True, verbose_name='\u0414\u0430\u0442\u0430 \u044d\u043a\u0437\u0430\u043c\u0435\u043d\u0430'),
        ),
    ]
